languageName: Українська (Ukrainian)
languageCode: uk-UA
params:
  description: Сайт проєкту OpenTelemetry

  copyright:
    authors: >-
      Автори OpenTelemetry | Документація за Ліцензією [CC BY
      4.0](https://creativecommons.org/licenses/by/4.0/deed.uk)
    from_year: 2019
  tagline: Ефективна спостережуваність вимагає високоякісної телеметрії
  sub_tagline: >-
    **OpenTelemetry** робить надійну, портативну телеметрію вбудованою функцією
    хмарного програмного забезпечення.
  sub_description: >-
    **OpenTelemetry** надає єдиний набір API, бібліотек, агентів та
    сервісів-колекторів для збору розподілених трейсів та метрик з вашого
    застосунку. Ви можете аналізувати їх за допомогою Prometheus, Jaeger та
    інших інструментів спостереження.

  ui:
    feedback:
      'yes': >-
        Дякуємо. Ми цінуємо ваш відгук!
      'no': >-
        Будь ласка, повідомте нам <a class="external-link" target="_blank"
        rel="noopener"
        href="https://github.com/open-telemetry/opentelemetry.io/issues/new?template=PAGE_FEEDBACK.yml&title=[Page+feedback]%3A+ADD+A+SUMMARY+OF+YOUR+FEEDBACK+HERE">як
        ми можемо поліпшити цю сторінку</a>. Ми цінуємо ваш відгук!

  links:
    user:
      - name: Списки розсилки
        url: https://github.com/open-telemetry/community#mailing-lists
        icon: fa fa-envelope
        desc: Список списків розсилки, які використовує проєкт.
      - name: Bluesky
        url: https://bsky.app/profile/opentelemetry.io
        icon: fab fa-bluesky
        desc: Слідкуйте за нами на Bluesky, щоб отримувати останні новини!
      - name: Mastodon
        url: https://fosstodon.org/@opentelemetry
        icon: fab fa-mastodon
        desc: Слідкуйте за нами на Mastodon, щоб отримувати останні новини!
      - name: Stack Overflow
        url: https://stackoverflow.com/questions/tagged/open-telemetry
        icon: fab fa-stack-overflow
        desc: Практичні питання та перевірені відповіді
      - name: Логотипи OTel
        url: https://github.com/cncf/artwork/tree/master/projects/opentelemetry
        icon: fas fa-image
        desc: Офіційні логотипи OpenTelemetry
      - name: Записи зустрічей
        url: https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s
        icon: fas fa-video
        desc: Перегляньте записи наших зустрічей у Zoom Cloud
      - name: Аналітика сайту
        url: https://lookerstudio.google.com/s/tSTKxK1ECeU
        icon: fa-solid fa-chart-line
        desc: Google Analytics для opentelemetry.io
    developer:
      - name: GitHub
        url: https://github.com/open-telemetry
        icon: fab fa-github
        desc: Знайдіть нас на GitHub.
      - name: 'Slack #opentelemetry'
        url: https://cloud-native.slack.com/archives/CJFCJHG4Q
        icon: fab fa-slack
        desc: >-
          Спілкуйтеся з іншими розробниками проєкту. Зареєструйтеся на
          [slack.cncf.io](https://slack.cncf.io). Також перегляньте інші канали,
          що починаються з префікса `#otel-`.
      - name: CNCF DevStats
        url: https://opentelemetry.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m
        icon: fas fa-chart-area
        desc: Перегляньте нашу діяльність на CNCF DevStats
      - name: Політика конфіденційності
        url: https://www.linuxfoundation.org/legal/privacy-policy
        icon: fa fa-book
        desc: Політика конфіденційності CNCF та Linux Foundation.
      - name: Використання торгової марки
        url: https://www.linuxfoundation.org/legal/trademark-usage
        icon: fa-solid fa-trademark
        desc: Політика та рекомендації Linux Foundation щодо торговельних марок.
      - name: Рекомендації щодо маркетингу
        url: /community/marketing-guidelines/
        icon: fas fa-bullhorn
        desc: >-
          Важлива інформація про те, як представити ваші особисті або
          корпоративні внески або участь в проєкті OpenTelemetry.
      - name: Інформація про створення сайту
        url: /site/
        icon: fa-solid fa-hammer
        desc: Інформація про створення сайту.

  notes:
    docker-compose-v2: |
      `docker-compose` є застарілим. Детальніше див.
      [Migrate to Compose V2](https://docs.docker.com/compose/migrate/).
