languageName: English
languageCode: en-US
params:
  description: The OpenTelemetry Project Site

  copyright:
    authors: >-
      OpenTelemetry Authors | Docs [CC BY
      4.0](https://creativecommons.org/licenses/by/4.0)
    from_year: 2019
  tagline: Effective observability requires high-quality telemetry
  sub_tagline: >-
    **OpenTelemetry** makes robust, portable telemetry a built-in feature of
    cloud-native software.
  sub_description: >-
    **OpenTelemetry** provides a single set of APIs, libraries, agents, and
    collector services to capture distributed traces and metrics from your
    application. You can analyze them using Prometheus, Jaeger, and other
    observability tools.

  ui:
    feedback:
      'yes': >-
        Thank you. Your feedback is appreciated!
      'no': >-
        Please let us know <a class="external-link" target="_blank"
        rel="noopener"
        href="https://github.com/open-telemetry/opentelemetry.io/issues/new?template=PAGE_FEEDBACK.yml&title=[Page+feedback]%3A+ADD+A+SUMMARY+OF+YOUR+FEEDBACK+HERE">how
        we can improve this page</a>. Your feedback is appreciated!
  links:
    user:
      - name: Mailing Lists
        url: https://github.com/open-telemetry/community#mailing-lists
        icon: fa fa-envelope
        desc: List of mailing lists that the project uses.
      - name: Bluesky
        url: https://bsky.app/profile/opentelemetry.io
        icon: fab fa-bluesky
        desc: Follow us on Bluesky to get the latest news!
      - name: Mastodon
        url: https://fosstodon.org/@opentelemetry
        icon: fab fa-mastodon
        desc: Follow us on Mastodon to get the latest news!
      - name: Stack Overflow
        url: https://stackoverflow.com/questions/tagged/open-telemetry
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
      - name: OTel logos
        url: https://github.com/cncf/artwork/tree/master/projects/opentelemetry
        icon: fas fa-image
        desc: Official OpenTelemetry logos
      - name: Meeting Recordings
        url: https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s
        icon: fas fa-video
        desc: Watch our meeting recordings on Zoom Cloud
      - name: Site analytics
        url: https://lookerstudio.google.com/s/tSTKxK1ECeU
        icon: fa-solid fa-chart-line
        desc: Google analytics for opentelemetry.io
    developer:
      - name: GitHub
        url: https://github.com/open-telemetry
        icon: fab fa-github
        desc: Find us on GitHub.
      - name: 'Slack #opentelemetry'
        url: https://cloud-native.slack.com/archives/CJFCJHG4Q
        icon: fab fa-slack
        desc: >-
          Chat with other project developers. Sign up via
          [slack.cncf.io](https://slack.cncf.io). Also see other channels
          starting with a `#otel-` prefix.
      - name: CNCF DevStats
        url: https://opentelemetry.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m
        icon: fas fa-chart-area
        desc: See our activity on CNCF DevStats
      - name: Privacy Policy
        url: https://www.linuxfoundation.org/legal/privacy-policy
        icon: fa fa-book
        desc: CNCF and Linux Foundation privacy policy.
      - name: Trademark Usage
        url: https://www.linuxfoundation.org/legal/trademark-usage
        icon: fa-solid fa-trademark
        desc: Linux Foundation’s trademarks policy and guidelines.
      - name: Marketing Guidelines
        url: /community/marketing-guidelines/
        icon: fas fa-bullhorn
        desc: >-
          Important information on how to represent your personal or corporate
          contributions or participation in the OpenTelemetry project.
      - name: Site-build info
        url: /site/
        icon: fa-solid fa-hammer
        desc: Site-build information.

  notes:
    docker-compose-v2: |
      `docker-compose` is deprecated. For details, see
      [Migrate to Compose V2](https://docs.docker.com/compose/migrate/).
