blog:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/blog/**
registry:
  - changed-files:
      - any-glob-to-any-file:
          - data/registry/**

# Localization labels
i18n:
  - changed-files:
      - any-glob-to-any-file:
          - i18n/**
lang:bn:
  - changed-files:
      - any-glob-to-any-file:
          - content/bn/**
lang:es:
  - changed-files:
      - any-glob-to-any-file:
          - content/es/**
lang:fr:
  - changed-files:
      - any-glob-to-any-file:
          - content/fr/**
lang:ja:
  - changed-files:
      - any-glob-to-any-file:
          - content/ja/**
lang:pl:
  - changed-files:
      - any-glob-to-any-file:
          - content/pl/**
lang:pt:
  - changed-files:
      - any-glob-to-any-file:
          - content/pt/**
lang:ro:
  - changed-files:
      - any-glob-to-any-file:
          - content/ro/**
lang:uk:
  - changed-files:
      - any-glob-to-any-file:
          - content/uk/**
lang:zh:
  - changed-files:
      - any-glob-to-any-file:
          - content/zh/**

# Special Interest Groups labels
sig:collector:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/collector/**
sig:cpp:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/cpp/**
sig:demo:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/demo/**
sig:dotnet:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/net/**
          - content/en/docs/zero-code/net/**
sig:enduser:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/community/end-user/**
sig:erlang:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/erlang/**
sig:go:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/go/**
          - content/en/docs/zero-code/go/**
sig:helm:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/kubernetes/helm/**
sig:java:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/java/**
          - content/en/docs/zero-code/java/**
sig:javascript:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/js/**
          - content/en/docs/zero-code/js/**
sig:kotlin:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/kotlin/**
sig:obi:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/zero-code/obi/**
sig:operator:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/kubernetes/operator/**
sig:php:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/php/**
          - content/en/docs/zero-code/php/**
sig:python:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/python/**
          - content/en/docs/zero-code/python/**
sig:ruby:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/ruby/**
sig:rust:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/rust/**
sig:security:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/security/**
sig:spec:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/specs/**
sig:swift:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/swift/**

# CI & Infrastructure labels
CI/infra:
  - changed-files:
      - any-glob-to-any-file:
          - .devcontainer/**
          - .github/**
          - config/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - .gitmodules
