blog:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/blog/**
registry:
  - changed-files:
      - any-glob-to-any-file:
          - data/registry/**
lang:zh:
  - changed-files:
      - any-glob-to-any-file:
          - content/zh/**
lang:ja:
  - changed-files:
      - any-glob-to-any-file:
          - content/ja/**
lang:pt:
  - changed-files:
      - any-glob-to-any-file:
          - content/pt/**
lang:es:
  - changed-files:
      - any-glob-to-any-file:
          - content/es/**
sig:cpp:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/cpp/**
sig:erlang:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/erlang/**
sig:go:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/go/**
          - content/en/docs/zero-code/go/**
sig:java:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/java/**
          - content/en/docs/zero-code/java/**
sig:javascript:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/js/**
          - content/en/docs/zero-code/js/**
sig:dotnet:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/net/**
          - content/en/docs/zero-code/net/**
sig:php:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/php/**
          - content/en/docs/zero-code/php/**
sig:python:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/python/**
          - content/en/docs/zero-code/python/**
sig:ruby:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/ruby/**
sig:rust:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/rust/**
sig:swift:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/languages/swift/**
sig:operator:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/kubernetes/operator/**
sig:helm:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/kubernetes/helm/**
sig:security:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/security/**
sig:demo:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/demo/**
sig:collector:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/collector/**
sig:enduser:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/community/end-user/**
sig:spec:
  - changed-files:
      - any-glob-to-any-file:
          - content/en/docs/specs/**
