version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: hugo-extended
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
