#!/bin/bash
set -e
set -o pipefail

# This script synchronizes OpenTelemetry Collector component documentation
# from the ecosystem-registry (via ecosystem-explorer clone).

if [ -z "$GH_TOKEN" ]; then
  echo "Error: GH_TOKEN environment variable is required"
  exit 1
fi

gh auth status >/dev/null 2>&1 || { echo "Error: gh CLI authentication failed"; exit 1; }

if [ -z "$GITHUB_REPOSITORY" ]; then
  echo "Error: GITHUB_REPOSITORY environment variable is required"
  exit 1
fi

echo "Starting collector component documentation sync"

echo "Installing Node.js dependencies..."
npm install --omit=optional

echo "Installing Python dependencies..."
cd scripts/collector-sync || { echo "Error: Failed to change to scripts/collector-sync directory"; exit 1; }
uv sync

echo "Generating documentation..."
uv run python -m documentation_sync

cd ../.. || { echo "Error: Failed to return to repo root"; exit 1; }

echo "Formatting documentation..."
npm run fix:format

echo "Checking links..."
npm run check:links || echo "Warning: Link check failed"

# Get version info from cloned ecosystem-explorer registry
if [ ! -d "tmp_repos/opentelemetry-ecosystem-explorer" ]; then
  echo "Error: ecosystem-explorer repository not found"
  exit 1
fi

VERSION=$(ls -1 tmp_repos/opentelemetry-ecosystem-explorer/ecosystem-registry/collector/core 2>/dev/null | grep -v -i 'SNAPSHOT' | sort -V | tail -n 1)
if [ -z "$VERSION" ]; then
  echo "Error: No collector versions found"
  exit 1
fi
echo "Version: $VERSION"

if [ -f "metadata-issues.md" ]; then
  echo "Reporting metadata quality issues for version ${VERSION}..."

  ISSUE_TITLE="Collector ${VERSION} Metadata Quality Issues"

  ISSUE_NUMBER=$(gh issue list \
    --repo "$GITHUB_REPOSITORY" \
    --state open \
    --json number,title \
    --jq ".[] | select(.title == \"${ISSUE_TITLE}\") | .number | select(. != null)" | head -n 1)

  if [ -n "$ISSUE_NUMBER" ]; then
    echo "Updating existing issue #${ISSUE_NUMBER}..."
    UPDATED_BODY="## Metadata Quality Report for Collector ${VERSION}

$(cat metadata-issues.md)

---
_Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')_"

    gh issue edit "$ISSUE_NUMBER" \
      --repo "$GITHUB_REPOSITORY" \
      --body "$UPDATED_BODY" \
      --add-label "metadata-quality" || true
  else
    echo "Creating new issue..."
    gh issue create \
      --repo "$GITHUB_REPOSITORY" \
      --title "$ISSUE_TITLE" \
      --label "metadata-quality" \
      --body "$(cat metadata-issues.md)" || {
        gh issue create \
          --repo "$GITHUB_REPOSITORY" \
          --title "$ISSUE_TITLE" \
          --body "$(cat metadata-issues.md)"
      }
  fi

  rm -f metadata-issues.md
fi

echo "Checking for documentation changes..."
CHANGED_FILES=$(git diff --name-only content/en/docs/collector/components/)

if [ -z "$CHANGED_FILES" ]; then
  echo "No documentation changes detected"
  exit 0
fi

echo "Documentation changes detected:"
echo "$CHANGED_FILES"

BRANCH_NAME="otelbot/collector-docs-${VERSION//\./-}"
echo "Branch: $BRANCH_NAME"

echo "Creating branch and committing changes..."
git checkout -B "$BRANCH_NAME"
git add .

if git diff --staged --quiet; then
  echo "No changes to commit"
  exit 0
fi

git commit -m "Update Collector component tables for ${VERSION}"

echo "Pushing branch..."
git push -f origin "$BRANCH_NAME" || {
  echo "Error: Failed to push branch"
  exit 1
}

echo "Creating PR..."

PR_BODY="## Update Collector Component Documentation

This PR updates the OpenTelemetry Collector component tables for version **${VERSION}**.

---

🤖 _This PR was automatically generated by the collector-sync automation_"

if ! gh pr create \
  --repo "${GITHUB_REPOSITORY}" \
  --head "${BRANCH_NAME}" \
  --title "Update Collector component tables for ${VERSION}" \
  --body "$PR_BODY" 2>&1; then
  # PR likely already exists, try to update it
  PR_NUMBER="$(gh pr list \
    --repo "${GITHUB_REPOSITORY}" \
    --head "${BRANCH_NAME}" \
    --state open \
    --json number \
    --jq '.[0].number // empty')"
  if [ -n "$PR_NUMBER" ]; then
    echo "PR already exists, updating..."
    gh pr edit "$PR_NUMBER" \
      --repo "${GITHUB_REPOSITORY}" \
      --title "Update Collector component tables for ${VERSION}" \
      --body "$PR_BODY"
  else
    echo "Error: Failed to create or find existing PR"
    exit 1
  fi
fi

echo "Successfully created/updated PR"
