# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
language: en-US
import:
  - '@cspell/dict-es-es/cspell-ext.json'
  - '@cspell/dict-fr-fr/cspell-ext.json'
  - '@cspell/dict-pt-br/cspell-ext.json'
caseSensitive: true
ignorePaths:
  - '*.svg'
  - content/ja
  - content/zh
  - data/community/members.yaml
  - static/refcache.json
  - vendors.yaml
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end
      /igmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
dictionaryDefinitions:
  - name: en-words
    path: .cspell/en-words.txt
  - name: es-palabras
    path: .cspell/es-palabras.txt
  - name: fr-mots
    path: .cspell/fr-mots.txt
  - name: pt-palavras
    path: .cspell/pt-palavras.txt
dictionaries:
  # Natural languages
  - es-es
  - pt-br
  - fr-fr
  # Local word lists
  - en-words
  - es-palabras
  - fr-mots
  - pt-palavras
  # Programming languages and software terms
  - cpp
  - dotnet
  - golang
  - node
  - softwareTerms
  # Other
  - companies
words: # Valid words across all locales
  - Docsy
  - htmltest
