CacheExpires: 4400h # ~ 6 months
DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
IgnoreCanonicalBrokenLinks: false
CheckMailto: false
IgnoreInternalURLs: # list of paths
IgnoreURLs: # list of regexs of paths or URLs to be ignored
  - ^/docs/instrumentation/\w+/(api|examples)/$
  - ^/docs/instrumentation/net/(metrics-api|traces-api)/
  - ^/community/end-user/feedback-survey/$
  - ^(/docs/migration/)?opencensus/$

  # TODO(@chalin) remove once the website pages have caught up with latest semconv changes:
  - ^/docs/specs/otel/\w+/semantic_conventions
  - \#instrument-advice

  - ^https://deploy-preview-\d+--opentelemetry.netlify.app/
  - ^https://www\.googletagmanager\.com

  - ^https?://localhost\b
  - ^https?://127\.0\.0\.1\b
  - ^https?://(otel-demo|traefik)\.localhost

  # Sites that deny access, always yielding 403 Forbidden (unless mentioned otherwise)
  - ^https://(www\.)?linkedin\.com\b # 999 Request Denied
  - ^https://(www\.)?mvnrepository\.com
  - ^https://twitter.com
  - ^https://www.chathamhouse.org
  - ^https://www.zocdoc.com

  # Ignore Docsy-generated GitHub links:
  - ^https?://github\.com/.*?/.*?/(new|edit)/ # view-page, edit-source etc
  # TODO: drop after fix to https://github.com/google/docsy/issues/1432
  - ^https://github.com/open-telemetry/opentelemetry.io/commit/ # last mod

  # Ignore links to GH repo content for now.
  - ^https?://github\.com/.*?/.*?/(blob|tree)/

  # Too many redirects as the server tries to figure out the country and language,
  # e.g.: https://www.microsoft.com/en-ca/sql-server.
  - ^https://www.microsoft.com/sql-server$

  # TODO: drop after fix to https://github.com/rust-lang/crates.io/issues/788
  - ^https://crates\.io/crates
  # TODO: drop after fix to https://github.com/micrometer-metrics/micrometer-docs/issues/239
  - ^https://micrometer\.io/docs
  # TODO: drop after fix to https://github.com/google/docsy/issues/1337
  - ^https://opentelemetry\.io/.
  # TODO: drop after fix to https://github.com/open-telemetry/opentelemetry.io/issues/2354
  - ^https://open-telemetry\.github\.io/opentelemetry-python/benchmarks/
  # TODO: remove after merge of https://github.com/open-telemetry/opentelemetry.io/pull/2594
  - ^https://elastic.co/blog/ecs-elastic-common-schema-otel-opentelemetry-announcement
  # TODO: remove after OpAMP spec is fixed: https://github.com/open-telemetry/opamp-spec/issues/148
  - ^https://example.com:4318/v1/metrics
  - ^https://pdf.sciencedirectassets.com/280203/1-s2.0-S1877050919X0006X
  - ^https://research.fb.com/wp-content/uploads/2016/11/holistic-configuration-management-at-facebook.pdf
