DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
IgnoreInternalURLs: # list of paths
IgnoreURLs: # list of regexs to paths or URLs
  - ^/docs/instrumentation/\w+/(api|examples)/$
  - ^/docs/instrumentation/net/(metrics-api|traces-api)/
