# See https://github.com/DavidAnson/markdownlint/blob/main/README.md#rules--aliases

default: true

emphasis-style: false
first-line-h1: false
line-length: false
link-fragments: false
list-marker-space: false
no-emphasis-as-header: false
no-hard-tabs: false
no-inline-html: false
no-trailing-punctuation: false
no-trailing-spaces:
  br_spaces: 0
  strict: true
table-column-style: false # Causes problems in ja and zh pages

# Custom rules below this point:
trim-code-blank-lines: true
unindent-code-blocks: true
validate-links:
  patterns:
    - regex: "https://github\\.(?!com|blog|io)"
      message: >-
        GitHub URLs should use `github.(com|blog|io)` domains to avoid
        typosquatting. For details, see
        https://github.com/open-telemetry/opentelemetry.io/issues/8085
