customRules:
  - ./scripts/_md-rules/alert-type-not-translated.mjs
  - ./scripts/_md-rules/unindent-code-blocks.js
  - ./scripts/_md-rules/trim-code-blank-lines.js
  - ./scripts/_md-rules/link-rules.mjs

ignores:
  - '.github/**'
  - 'content-modules/**'
  - 'examples/**'
  - 'layouts/**'
  - '**/node_modules/**'
  - 'resources/**'
  - 'tools/**'
  - 'themes/**'
  - 'tmp/**'

config:
  extends: .markdownlint.yaml
