customRules:
  - ./scripts/_md-rules/alert-type-not-translated.mjs
  - ./scripts/_md-rules/unindent-code-blocks.js
  - ./scripts/_md-rules/trim-code-blank-lines.js
  - ./scripts/_md-rules/link-rules.mjs
  - markdownlint-rule-no-shortcut-ref-link

ignores:
  - '.github/**'
  - 'content-modules/**'
  - 'examples/**'
  - 'layouts/**'
  - '**/node_modules/**'
  - 'resources/**'
  - 'tools/**'
  - 'themes/**'

config:
  extends: .markdownlint.yaml
