# cSpell:ignore bluesky cicd docsy goldmark linkify netlify wordmark noopener
baseURL: https://opentelemetry.io
title: OpenTelemetry
disableKinds: [taxonomy]
theme: [docsy]
disableAliases: true # We do redirects via Netlify's _redirects file
enableGitInfo: true

# Language settings
defaultContentLanguage: en
#
# TODO: Disabling the following for the duration of the Ask AI trial. If we
# decide to keep Ask AI, then locales should provide Ask-AI i18n key entries
# and the following should be re-enabled / uncommented.
#
# enableMissingTranslationPlaceholders: true

languages:
  en:
    languageName: English
    languageCode: en-US
    params:
      description: The OpenTelemetry Project Site
  bn:
    languageName: বাংলা (Bengali)
    params:
      description: ওপেনটেলিমেট্রি প্রকল্পের সাইট
  es:
    languageName: Español
    params:
      description: Sitio del proyecto OpenTelemetry
  fr:
    languageName: Français
    params:
      description: Site du projet OpenTelemetry
  ja:
    languageName: 日本語 (Japanese)
    params:
      description: OpenTelemetryプロジェクト公式サイト
      notes:
        docker-compose-v2: |
          `docker-compose` は非推奨です. 詳細は、
          [Migrate to Compose V2](https://docs.docker.com/compose/migrate/) を確認してください。
  pt: # cSpell:ignore Português Projeto
    languageName: Português
    languageCode: pt-BR
    params:
      description: Site do Projeto OpenTelemetry
  ro:
    languageName: Română (Romanian)
    languageCode: ro-RO
    params:
      description: Site-ul proiectului OpenTelemetry
  uk:
    languageName: Українська (Ukrainian)
    languageCode: uk-UA
    params:
      description: Сайт проєкту OpenTelemetry
  zh:
    languageName: 中文 (Chinese)
    languageCode: zh-CN
    params:
      description: OpenTelemetry 项目网站

imaging:
  resampleFilter: CatmullRom # cspell:disable-line
  quality: 75
  anchor: smart

markup:
  tableOfContents:
    endLevel: 5
  goldmark:
    extensions:
      linkify: false
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: false
    renderer:
      unsafe: true
  highlight:
    noClasses: false

# Netlify _redirects file
mediaTypes:
  text/netlify: {}

outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
    notAlternative: true

outputs:
  home: [HTML, RSS]
  section: [HTML]

services:
  rss: { limit: 20 }

cascade:
  build: { list: never, publishResources: false, render: never }
  _target: { path: '{,/**}/_includes{,/**}' }

params:
  copyright:
    authors: >-
      OpenTelemetry Authors | Docs [CC BY
      4.0](https://creativecommons.org/licenses/by/4.0)
    from_year: 2019
  tagline: Effective observability requires high-quality telemetry
  sub_tagline: >-
    **OpenTelemetry** makes robust, portable telemetry a built-in feature of
    cloud-native software.
  sub_description: >-
    **OpenTelemetry** provides a single set of APIs, libraries, agents, and
    collector services to capture distributed traces and metrics from your
    application. You can analyze them using Prometheus, Jaeger, and other
    observability tools.
  github_repo: https://github.com/open-telemetry/opentelemetry.io
  github_branch: main
  gcs_engine_id: 015faf7de29c34606

  ## Social media image path, such as Open Graph's og:image
  #
  # IMPORTANT: if you change the image but not the path, also increment the
  # version ID in the filename below. Otherwise, for new paths, start at version
  # `001`. Note that social-media images must be preserved (or redirected)
  # forever.
  images:
    - img/social/logo-wordmark-001.png

  ui:
    navbar_logo: true
    navbar_translucent_over_cover_disable: true
    showLightDarkModeMenu: true
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_search_disable: true
    feedback:
      enable: true
      'yes': >-
        Thank you. Your feedback is appreciated!
      # prettier-ignore
      'no': >-
        Please let us know <a class="external-link" target="_blank" rel="noopener"
        href="https://github.com/open-telemetry/opentelemetry.io/issues/new?template=PAGE_FEEDBACK.yml&title=[Page+feedback]%3A+ADD+A+SUMMARY+OF+YOUR+FEEDBACK+HERE">how
        we can improve this page</a>. Your feedback is appreciated!
  links:
    user:
      - name: Mailing Lists
        url: https://github.com/open-telemetry/community#mailing-lists
        icon: fa fa-envelope
        desc: List of mailing lists that the project uses.
      - name: Bluesky
        url: https://bsky.app/profile/opentelemetry.io
        icon: fab fa-bluesky
        desc: Follow us on Bluesky to get the latest news!
      - name: Mastodon
        url: https://fosstodon.org/@opentelemetry
        icon: fab fa-mastodon
        desc: Follow us on Mastodon to get the latest news!
      - name: Stack Overflow
        url: https://stackoverflow.com/questions/tagged/open-telemetry
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
      - name: OTel logos
        url: https://github.com/cncf/artwork/tree/master/projects/opentelemetry
        icon: fas fa-image
        desc: Official OpenTelemetry logos
      - name: Meeting Recordings
        url: https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s
        icon: fas fa-video
        desc: Watch our meeting recordings on Zoom Cloud
      - name: Site analytics
        url: https://lookerstudio.google.com/s/tSTKxK1ECeU
        icon: fa-solid fa-chart-line
        desc: Google analytics for opentelemetry.io
    developer:
      - name: GitHub
        url: https://github.com/open-telemetry
        icon: fab fa-github
        desc: Find us on GitHub.
      - name: 'Slack #opentelemetry'
        url: https://cloud-native.slack.com/archives/CJFCJHG4Q
        icon: fab fa-slack
        desc: >-
          Chat with other project developers. Sign up via
          [slack.cncf.io](https://slack.cncf.io). Also see other channels
          starting with a `#otel-` prefix.
      - name: CNCF DevStats
        url: https://opentelemetry.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m
        icon: fas fa-chart-area
        desc: See our activity on CNCF DevStats
      - name: Privacy Policy
        url: https://www.linuxfoundation.org/legal/privacy-policy
        icon: fa fa-book
        desc: CNCF and Linux Foundation privacy policy.
      - name: Trademark Usage
        url: https://www.linuxfoundation.org/legal/trademark-usage
        icon: fa-solid fa-trademark
        desc: Linux Foundation’s trademarks policy and guidelines.
      - name: Marketing Guidelines
        url: /community/marketing-guidelines/
        icon: fas fa-bullhorn
        desc: >-
          Important information on how to represent your personal or corporate
          contributions or participation in the OpenTelemetry project.
      - name: Site-build info
        url: /site/
        icon: fa-solid fa-hammer
        desc: Site-build information.

  logos:
    hero: opentelemetry-horizontal-color.png
    cncf: cncf.png

  social:
    - name: GitHub
      url: https://github.com/open-telemetry/
      color: black
      icon: fab fa-github
    - name: X
      url: https://x.com/opentelemetry
      color: twitter
      icon: fab fa-x-twitter
    - name: Slack
      url: https://cloud-native.slack.com/archives/CJFCJHG4Q
      color: slack
      icon: fab fa-slack
    - name: Medium
      url: https://medium.com/opentelemetry
      color: light
      icon: fab fa-medium
    - name: Mailing list
      url: https://lists.cncf.io/g/cncf-opentelemetry-community
      color: info
      icon: far fa-envelope

  fonts:
    - name: Noto Sans # cspell:disable-line
      sizes: [300, 400, 600, 700]
      type: sans_serif

  notes:
    # Syntax is markdown. This params section is the default for `en` and
    # fallback for other languages. Add locale specific entries under the
    # top-level `languages.XX.params` entry for your locale XX.
    docker-compose-v2: |
      `docker-compose` is deprecated. For details, see
      [Migrate to Compose V2](https://docs.docker.com/compose/migrate/).

security:
  funcs: # cspell:disable-line
    getenv: # cspell:disable-line
      # Netlify build env var
      - ^(BRANCH|BUILD_ID|COMMIT_REF|CONTEXT|DEPLOY_ID|NETLIFY|PULL_REQUEST|REVIEW_ID)$

module:
  mounts:
    ## en
    - source: content/en
      target: content
    - source: tmp/community/mission-vision-values.md
      target: content/community/mission.md
    - source: tmp/community/roadmap.md
      target: content/community/roadmap.md
    # Specs, currently en only
    - source: tmp/otel/specification
      target: content/docs/specs/otel
    - source: tmp/opamp
      target: content/docs/specs/opamp
    - source: tmp/otlp/docs/specification.md
      target: content/docs/specs/otlp/_index.md
    - source: tmp/otlp/docs/img
      target: content/docs/specs/otlp/img
    # Semconv
    # cSpell:ignore cloudevents faas
    - source: tmp/semconv/docs
      target: content/docs/specs/semconv
      excludeFiles: '**/README.md'
    # DO NOT EDIT - semconv autogenerated mounts below this point - DO NOT EDIT
    - source: tmp/semconv/docs/azure/README.md
      target: content/docs/specs/semconv/azure/_index.md
    - source: tmp/semconv/docs/cicd/README.md
      target: content/docs/specs/semconv/cicd/_index.md
    - source: tmp/semconv/docs/cloud-providers/README.md
      target: content/docs/specs/semconv/cloud-providers/_index.md
    - source: tmp/semconv/docs/cloudevents/README.md
      target: content/docs/specs/semconv/cloudevents/_index.md
    - source: tmp/semconv/docs/code/README.md
      target: content/docs/specs/semconv/code/_index.md
    - source: tmp/semconv/docs/database/README.md
      target: content/docs/specs/semconv/database/_index.md
    - source: tmp/semconv/docs/dotnet/README.md
      target: content/docs/specs/semconv/dotnet/_index.md
    - source: tmp/semconv/docs/exceptions/README.md
      target: content/docs/specs/semconv/exceptions/_index.md
    - source: tmp/semconv/docs/faas/README.md
      target: content/docs/specs/semconv/faas/_index.md
    - source: tmp/semconv/docs/feature-flags/README.md
      target: content/docs/specs/semconv/feature-flags/_index.md
    - source: tmp/semconv/docs/gen-ai/README.md
      target: content/docs/specs/semconv/gen-ai/_index.md
    - source: tmp/semconv/docs/general/README.md
      target: content/docs/specs/semconv/general/_index.md
    - source: tmp/semconv/docs/hardware/README.md
      target: content/docs/specs/semconv/hardware/_index.md
    - source: tmp/semconv/docs/how-to-write-conventions/README.md
      target: content/docs/specs/semconv/how-to-write-conventions/_index.md
    - source: tmp/semconv/docs/http/README.md
      target: content/docs/specs/semconv/http/_index.md
    - source: tmp/semconv/docs/messaging/README.md
      target: content/docs/specs/semconv/messaging/_index.md
    - source: tmp/semconv/docs/mobile/README.md
      target: content/docs/specs/semconv/mobile/_index.md
    - source: tmp/semconv/docs/non-normative/compatibility/README.md
      target: content/docs/specs/semconv/non-normative/compatibility/_index.md
    - source: tmp/semconv/docs/non-normative/README.md
      target: content/docs/specs/semconv/non-normative/_index.md
    - source: tmp/semconv/docs/object-stores/README.md
      target: content/docs/specs/semconv/object-stores/_index.md
    - source: tmp/semconv/docs/README.md
      target: content/docs/specs/semconv/_index.md
    - source: tmp/semconv/docs/registry/attributes/README.md
      target: content/docs/specs/semconv/registry/attributes/_index.md
    - source: tmp/semconv/docs/registry/entities/README.md
      target: content/docs/specs/semconv/registry/entities/_index.md
    - source: tmp/semconv/docs/registry/README.md
      target: content/docs/specs/semconv/registry/_index.md
    - source: tmp/semconv/docs/resource/cloud-provider/aws/README.md
      target: content/docs/specs/semconv/resource/cloud-provider/aws/_index.md
    - source: tmp/semconv/docs/resource/cloud-provider/gcp/README.md
      target: content/docs/specs/semconv/resource/cloud-provider/gcp/_index.md
    - source: tmp/semconv/docs/resource/cloud-provider/README.md
      target: content/docs/specs/semconv/resource/cloud-provider/_index.md
    - source: tmp/semconv/docs/resource/README.md
      target: content/docs/specs/semconv/resource/_index.md
    - source: tmp/semconv/docs/rpc/README.md
      target: content/docs/specs/semconv/rpc/_index.md
    - source: tmp/semconv/docs/runtime/README.md
      target: content/docs/specs/semconv/runtime/_index.md
    - source: tmp/semconv/docs/system/README.md
      target: content/docs/specs/semconv/system/_index.md
    # DO NOT EDIT - semconv autogenerated mounts above - DO NOT EDIT

    ## bn
    - source: content/bn
      target: content
      lang: bn
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: bn
    - source: content/en/announcements
      target: content/announcements
      lang: bn
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: bn

    ## es
    - source: content/es
      target: content
      lang: es
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: es
    - source: content/en/announcements
      target: content/announcements
      lang: es
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: es

    ## fr
    - source: content/fr
      target: content
      lang: fr
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: fr
    - source: content/en/announcements
      target: content/announcements
      lang: fr
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: fr
    # - source: content/en/ecosystem
    #   target: content/ecosystem
    #   lang: fr

    ## ja
    - source: content/ja
      target: content
      lang: ja
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: ja
    - source: content/en/announcements
      target: content/announcements
      lang: ja
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: ja

    ## ro
    - source: content/ro
      target: content
      lang: ro
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: ro
    - source: content/en/announcements
      target: content/announcements
      lang: ro
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: ro

    ## uk
    - source: content/uk
      target: content
      lang: uk
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: uk
    - source: content/en/announcements
      target: content/announcements
      lang: uk
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: uk

    ## zh
    - source: content/zh
      target: content
      lang: zh
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: zh
    - source: content/en/announcements
      target: content/announcements
      lang: zh
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: zh

    ## pt
    - source: content/pt
      target: content
      lang: pt
    # fallback pages
    - source: content/en/_includes
      target: content/_includes
      lang: pt
    - source: content/en/announcements
      target: content/announcements
      lang: pt
    - excludeFiles: specs/*
      source: content/en/docs
      target: content/docs
      lang: pt
    - source: content/en/ecosystem
      target: content/ecosystem
      lang: pt

    ## static
    - source: static
      target: static
    - source: content-modules/semantic-conventions/schemas
      target: static/schemas
    - source: static/img
      target: static/img
    - source: content-modules/opentelemetry-specification/internal/img
      target: static/img
    - source: iconography/32x32
      target: static/img/logos/32x32
