[build]
publish = "public"
command = "npm run netlify-build:preview"

[context.production]
command = "npm run netlify-build:production"

[[redirects]]
from = "https://docs.opentelemetry.io/*"
to = "https://opentelemetry.io/docs/:splat"
force = true

[[redirects]]
from = "https://blog.opentelemetry.io/*"
to = "https://opentelemetry.io/blog/:splat"
force = true

[[edge_functions]]
function = "markdown-negotiation"
path = "/*"

[[edge_functions]]
function = "schema-analytics"
path = "/schemas/*"

[[edge_functions]]
function = "asset-tracking"
pattern = "/(.*)\\.(md)$"

# cSpell:ignore nosniff sameorigin

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self';"
