name: Website issue/bug
description: Report a problem with the opentelemetry.io site.
title: 'bug: '
type: bug
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: &what Describe the problem that occurred.
      placeholder: *what
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: What did you expect would happen?
      description: &expected Describe the expected result/output.
      placeholder: *expected
    validations:
      required: true

  - type: input
    id: page_path
    attributes:
      label: Name + path of the page
      description: >-
        The relative path and page title where you found a problem.
      placeholder: >-
        E.g., content/en/docs/concepts/what-is-otel.md — "What is
        OpenTelemetry?"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Browser, OS, and platform
      description: >-
        Include the browser version if you know it as well.
      placeholder: >-
        E.g., Chrome 120 on macOS 14 (Apple Silicon)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Anything else that would be helpful.
      placeholder: Links, screenshots, related issues/PRs, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: >-
        <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/)
        with 👍 to help prioritize this issue. Use comments to provide useful
        context, avoid `+1` or `me too`, to help us triage it. [Learn
        more](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
