name: Page Feedback
description: >-
  Used for page feedback from users visiting opentelemetry.io and clicking "no"
  if a page was helpful.
title: '[Page Feedback]: summary of your feedback'
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: >-
        The URL of the webpage where you are facing an issue. If not
        auto-populated, please copy the URL from the browser address bar.
      placeholder: https://opentelemetry.io/
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        'How has the page not been helpful? What information is missing? '
      placeholder: >-
        Provide details on the problem. The more information you share with us
        the faster we can resolve the issue.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tip
      description:
        This element is static, used to render a helpful sub-heading for
        end-users and community members to help prioritize issues. Please leave
        as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/)
          with 👍 to help prioritize this issue. Please use comments to provide
          useful context, avoiding `+1` or `me too`, to help us triage it. Learn
          more
          [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
