name: Page Feedback
description: >-
  Used for page feedback from users visiting opentelemetry.io and clicking "no"
  if a page was helpful.
title: '[Page Feedback]: summary of your feedback'
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: >-
        The URL of the webpage where you are facing an issue. If not
        auto-populated, please copy the URL from the browser address bar.
      placeholder: https://opentelemetry.io/
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        'How has the page not been helpful? What information is missing? '
      placeholder: >-
        Provide details on the problem. The more information you share with us
        the faster we can resolve the issue.
    validations:
      required: true
