name: fail-if-branch-is-main
description:
  Fail if PR branch name is 'main' and it is from a forked repository.
runs:
  using: composite
  steps:
    - name: Print PR and repo info
      run: |
        echo "Repo: ${GITHUB_REPOSITORY}"
        echo "Head Repo: ${GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FULL_NAME}"
        echo "Forked: ${GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FORK}"
        echo "Branch: ${GITHUB_EVENT_PULL_REQUEST_HEAD_REF}"
      shell: bash
      env:
        GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FULL_NAME:
          ${{ github.event.pull_request.head.repo.full_name }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FORK:
          ${{ github.event.pull_request.head.repo.fork }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_REF:
          ${{ github.event.pull_request.head.ref }}
    - if: github.event_name == 'pull_request'
      run: |
        if [ "${GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FORK}" == "true" ] && [ "${GITHUB_EVENT_PULL_REQUEST_HEAD_REF}" == 'main' ]; then
          echo "PR branch name cannot be 'main' when from forked repositories."
          echo "Resubmit your PR with a different branch name."
          exit 1
        fi
      shell: bash
      env:
        GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FORK:
          ${{ github.event.pull_request.head.repo.fork }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_REF:
          ${{ github.event.pull_request.head.ref }}
#
# Inspired by https://github.com/jaegertracing/jaeger/blob/main/.github/actions/block-pr-from-main-branch
