#!/usr/bin/perl

use strict;
use warnings;

my $gD = 0;

sub main {
    my @ignore_dirs;
    my @drifted_ignore_dirs;

    collect_htmltest_config_from_front_matter(\@ignore_dirs, \@drifted_ignore_dirs, @ARGV);
    update_htmltest_config_file(\@ignore_dirs, \@drifted_ignore_dirs);
}

sub collect_htmltest_config_from_front_matter {
    my ($ignore_dirs_ref, $drifted_ignore_dirs_ref, @files) = @_;

    foreach my $file_path (sort @files) {
        my $drifted_dir = extract_drifted_ignore_dir($file_path);
        push @$drifted_ignore_dirs_ref, $drifted_dir if defined $drifted_dir;

        my @htmltest_config = extract_htmltest_config($file_path);
        next unless @htmltest_config;
        push @$ignore_dirs_ref, @htmltest_config;
    }
}

sub extract_drifted_ignore_dir {
    # If $file_path is a drifted localized page (drifted_from_default: true in
    # front matter), return an end-anchored IgnoreDirs regex for its output
    # directory; otherwise return undef.
    #
    # Link checking originating from drifted pages is skipped (their links may be
    # stale), but the pages are still resolvable as anchor targets, so inbound
    # links from non-drifted pages keep being validated.
    my ($file_path) = @_;

    open my $fh, '<', $file_path or die "Could not open '$file_path': $!";
    my $content = do { local $/; <$fh> };
    close $fh;

    return unless $content =~ /---\n(.*?)\n---/s;
    my $front_matter = $1;
    return unless $front_matter =~ /^drifted_from_default:\s*true\s*$/m;

    # Strip the leading 'content/' source prefix.
    my $path = $file_path;
    $path =~ s{^\./}{};
    return unless $path =~ s{^content/}{};

    # Skip files under underscore-prefixed directories (e.g. '_includes'): they
    # are fragments, not standalone output pages.
    return if $path =~ m{(^|/)_[^/]+/};

    # Map the source file to its pretty-URL output directory.
    if ($path =~ m{^(.*)/(?:_index|index)\.(?:md|html)$}) {
        $path = $1; # section or leaf-bundle: directory is the URL
    } else {
        $path =~ s{\.(?:md|html)$}{}; # leaf page: filename slug is the URL segment
    }

    return "^$path/\$";
}

sub extract_htmltest_config {
    # Returns list of htmlconfig lines extracted from the front matter of $file_path
    my ($file_path) = @_;

    open my $fh, '<', $file_path or die "Could not open '$file_path': $!";
    my $content = do { local $/; <$fh> };
    close $fh;

    return unless $content =~ /---\n(.*?)\n---/s;

    my $front_matter = $1;
    my @htmltest_config = _extract_htmltest_config($front_matter);

    return unless @htmltest_config;

    if (@htmltest_config == 1) {
        warn "WARNING: Failed to extract htmltest config from front matter in file '$file_path'.\n";
        return;
    }

    do {
      shift @htmltest_config;
    } until !@htmltest_config # No more config
       || $htmltest_config[0] !~ /^\s*#/; # Non-comment line

    return _extract_ignore_dirs($file_path, @htmltest_config) if $htmltest_config[0] =~ /^IgnoreDirs:/i;

    # TODO: Add support for `IgnoreURLs`.

    warn "WARNING: Unrecognized htmltest config from front matter in file '$file_path'.\n";
}

sub _extract_ignore_dirs {
    my ($file_path,
        @ignore_dirs_config_lines # Can include comment lines
    ) = @_;
    my @config;

    foreach my $line (@ignore_dirs_config_lines) {
      next if $line =~ /^IgnoreDirs:\s*$/i;
      if ($line =~ /\s*#/) {
        push @config, $line;
      } elsif ($line =~ /^IgnoreDirs:\s*\[\s*(.*?)\s*\]/i || $line =~ /^\s*-\s*(.*?)$/) {
        push @config, (split /\s*,\s*/, $1);
      } else {
        warn "WARNING: Unrecognized htmltest IgnoreDirs config from front matter in file '$file_path': $line\n";
      }
    }
    return @config;
}

sub _extract_htmltest_config {
    # Returns a list of htmltest config lines with whitespace trimmed away.

    my ($front_matter) = @_;
    my @lines = split /\n/, $front_matter;
    my @htmltest_lines;
    my $in_htmltest_section = 0;

    foreach my $line (@lines) {
        if ($line =~ /^htmltest:(.*?)(#.*)?$/) {
            $in_htmltest_section = 1;
            push @htmltest_lines, $line;
        } elsif ($in_htmltest_section) {
            if ($line =~ /^(\s{2,})(.*)$/) {
                push @htmltest_lines, $2;
                printf "  > Config line: $line" if $gD;
            } else {
                last;
            }
        }
    }
    return @htmltest_lines;
}

sub update_htmltest_config_file {
    my ($ignore_dirs_ref, $drifted_ignore_dirs_ref) = @_;
    my $base_config_path = '.htmltest.base.yml';
    my $htmltest_config_path = '.htmltest.yml';
    my $generated_banner = "# GENERATED by 'npm run fix:htmltest-config' from $base_config_path -- DO NOT EDIT.\n";
    my $do_not_edit_msg = "  # DO NOT EDIT! IgnoreDirs list is auto-generated from markdown file front matter.\n";
    my $drifted_msg = "  # Drifted localized pages (drifted_from_default: true):\n";

    # Read the static base config as an array of lines.
    open my $fh, '<', $base_config_path or die "Could not open '$base_config_path' for reading: $!";
    my @lines = <$fh>;
    close $fh;

    # Drop the base file's leading comment header (its explanation of how the
    # generated file is produced); the generated file gets its own banner below.
    shift @lines while @lines && $lines[0] =~ /^\s*#/;

    # Fill the (empty) IgnoreDirs section with the generated entries.
    my $in_ignore_dirs = 0;
    my @new_lines = ($generated_banner);
    foreach my $line (@lines) {
        if ($line =~ /^IgnoreDirs:/) {
            push @new_lines, ($line, $do_not_edit_msg);
            foreach my $ignore_dir (@$ignore_dirs_ref) {
                my $prefix = $ignore_dir =~ /^#/ ? '  ' : '  - ';
                push @new_lines, "$prefix$ignore_dir\n";
            }
            if (@$drifted_ignore_dirs_ref) {
                push @new_lines, $drifted_msg;
                foreach my $drifted_dir (sort @$drifted_ignore_dirs_ref) {
                    push @new_lines, "  - $drifted_dir\n";
                }
            }
            push @new_lines, $do_not_edit_msg;
            $in_ignore_dirs = 1;
        } elsif ($in_ignore_dirs) {
            next if $line =~ /^\s*([#-]|$)/;
            $in_ignore_dirs = 0;
            push @new_lines, $line;
        } else {
            push @new_lines, $line;
        }
    }

    open my $fh_out, '>', $htmltest_config_path or die "Could not open '$htmltest_config_path' for writing: $!";
    print $fh_out @new_lines;
    close $fh_out;
}

main();
