name: Auto-update community members page

on:
  workflow_dispatch:
  schedule:
    # At 03:41, every day
    - cron: 41 3 * * *

permissions:
  contents: read

jobs:
  auto-update:
    name: Auto-update community members page
    runs-on: ubuntu-latest
    # Remove the if statement below when testing against a fork
    if: github.repository == 'open-telemetry/opentelemetry.io'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./scripts/generate-community-data
        run: npm install

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          # the higher privileged docs token is needed to push commits to an existing PR
          client-id: ${{ vars.OTELBOT_DOCS_APP_ID }}
          private-key: ${{ secrets.OTELBOT_DOCS_PRIVATE_KEY }}

      - name: Run script
        working-directory: ./scripts/generate-community-data
        run: node generate.js ../../data/community/members.yaml
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}

      - name: Use CLA approved github bot
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

      - name: Fix refcache
        run: |
          npm install --omit=optional
          npm run fix:refcache

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: |
            data/community/members.yaml
            static/refcache.json
          author: otelbot <197425009+otelbot@users.noreply.github.com>
          committer: otelbot <197425009+otelbot@users.noreply.github.com>
          token: ${{ steps.otelbot-token.outputs.token }}
          branch: otelbot/update-community-members
          title: Update community members
          body: |
            This pull request contains automated updates to files by the GitHub Action.

  report-failure:
    needs: auto-update
    if: failure() && github.repository == 'open-telemetry/opentelemetry.io'
    uses: ./.github/workflows/reusable-report-failure.yml
    permissions:
      issues: write # Pass through for failure tracking issues
      contents: read
