name: Check text linter rules # cSpell:ignore refcache

on:
  pull_request:

jobs:
  check-formatting:
    name: Check text linter rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm install
      - run: npm run check:textlint
