name: Check text linter rules # cSpell:ignore refcache

on:
  pull_request:

jobs:
  check-formatting:
    name: Check text linter rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:textlint
