name: Check text linter rules # cSpell:ignore refcache startswith

on:
  pull_request:

jobs:
  check-formatting:
    name: Check text linter rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      # Make sure that we only install the dependencies for textlint to speed up install
      - run: |
          jq 'del(.dependencies) | del(.scripts) | .devDependencies |= with_entries( select(.key | startswith("textlint") ) )' package.json > package2.json && mv package2.json package.json
      - run: npm ci
      - run: npm run check:textlint
