name: Survey on Merged PR by Non-Member

on:
  pull_request_target:
    types: [closed]

env:
  PR_NUM: ${{ github.event.pull_request.number }}
  SURVEY_URL: https://forms.gle/WV58koUBGSG9HBY66

permissions:
  contents: read

jobs:
  comment-on-pr:
    name: Add survey to PR if author is not a member
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.merged == true
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check if user is a member of the org
        id: check-membership
        run: |
          USERNAME=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          ORG="${{ github.repository_owner }}"
          STATUS=$(gh api "orgs/$ORG/members/$USERNAME" --silent && echo "true" || echo "false")
          if [[ "$STATUS" == "true" ]]; then
            echo "MEMBER_FOUND=true" >> $GITHUB_ENV
          else
            echo "MEMBER_FOUND=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}

      - name: Add comment to PR if author is not a member
        if: env.MEMBER_FOUND == 'false'
        run: |
          gh pr comment ${PR_NUM} --repo open-telemetry/opentelemetry.io --body "Thank you for your contribution! 🎉 We would like to hear from you about your experience contributing to OpenTelemetry by taking a few minutes to fill out this survey: ${SURVEY_URL}"
        env:
          GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
